// Generated by https://github.com/zhyupe/ffxiv-opcode-worker

namespace FFXIVOpcodes.CN
{
    enum ServerLobbyIpcType : ushort
    {

    };

    enum ClientLobbyIpcType : ushort
    {

    };

    enum ServerZoneIpcType : ushort
    {        
        // Server Zone
        PrepareZoning = 0x0318,
        PlayerStats = 0x01E5,
        
        PlayerSetup = 0x01BF,
        ActorControl = 0x008B,
        ActorControlSelf = 0x0190,
        UpdateClassInfo = 0x006F,
        ActorCast = 0x01E6,
        InitZone = 0x036E,
        WeatherChange = 0x03D4,
        EffectResult = 0x02D5,
        EventStart = 0x02C1,
        EventPlay = 0x014D,
        EventFinish = 0x0107,
        SomeDirectorUnk4 = 0x00BE,
        EventPlay4 = 0x00F1,
        Effect = 0x0085,
        StatusEffectList = 0x0287,
    };

    enum ClientZoneIpcType : ushort
    {
        ClientTrigger = 0x03C1,
    };

    enum ServerChatIpcType : ushort
    {

    };

    enum ClientChatIpcType : ushort
    {

    };
}
