// Generated by https://github.com/zhyupe/ffxiv-opcode-worker

namespace FFXIVOpcodes.CN
{
    enum ServerLobbyIpcType : ushort
    {

    };

    enum ClientLobbyIpcType : ushort
    {

    };

    enum ServerZoneIpcType : ushort
    {        
        // Server Zone
        ActorCast = 0x0116,
        ActorControl = 0x00CA,
        ActorControlSelf = 0x0245,
        Effect = 0x032E,
        EffectResult = 0x02E8,
        EventFinish = 0x01C2,
        EventPlay = 0x0276,
        EventPlay4 = 0x028C,
        EventStart = 0x00EC,
        InitZone = 0x01D6,
        PlayerSetup = 0x0194,
        PlayerStats = 0x017F,
        PrepareZoning = 0x02D8,
        SomeDirectorUnk4 = 0x0202,
        StatusEffectList = 0x015E,
        UpdateClassInfo = 0x0192,
        WeatherChange = 0x027A,
    };

    enum ClientZoneIpcType : ushort
    {
        // Client Zone
        ClientTrigger = 0x03B9,
    };

    enum ServerChatIpcType : ushort
    {

    };

    enum ClientChatIpcType : ushort
    {

    };
}
